"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

list: list = []
sum: int = 0

lastInt: int = 1
crntNum: int = 2

while True:
    if crntNum >= 4_000_000:
        break
    else:
        ts: int = crntNum + lastInt
        lastInt = crntNum
        crntNum = ts
        if crntNum % 2 == 0:
            list.append(crntNum)
            
for num in list:
    sum += num
print(sum+2)